# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-23 20:59
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('wikifinder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordsCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wikifinder.Article')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wikifinder.Words')),
            ],
        ),
    ]
