# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-24 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('wikifinder', '0002_wordscount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleToMatrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.IntegerField()),
                ('col_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Matrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField()),
                ('col', models.IntegerField()),
                ('data', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WordToMatrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_id', models.TextField()),
                ('row_no', models.IntegerField()),
            ],
        ),
    ]
